db:
  username: postgres
  password: esl2
  host: news-db
  port: 5432
  database: postgres
  echo: False
logger:
  level: INFO
agency:
  dailynews:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 10
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_dailynews:
    - https://www.dailynews.co.th/news/news_group/เศรษฐกิจ-ยานยนต์/
    - https://www.dailynews.co.th/news/news_group/ต่างประเทศ/
    - https://www.dailynews.co.th/news/news_group/การศึกษา-ไอที/
    - https://www.dailynews.co.th/news/news_group/อื่นๆ/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/บันเทิง/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/กีฬา/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/การเมือง/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/อาชญากรรม/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/ทั่วไทย-กทม/ #หมวดใหม่
  mgronline:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 10
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_mgronline:
     - https://mgronline.com/stockmarket/4920/ #หุ้น-Cryptocurrency
     - https://mgronline.com/science/5516/5528/ #วิทยาศาสตร์-นวตกรรม-สิ่งประดิษฐ์โทคโนฯ
     - https://mgronline.com/science/5504/5530/ #วิทยาศาสตร์-อวกาศ-เทคโนโลยีอวกาศ
     - https://mgronline.com/business/4450/4401/ #เศรษฐกิจ-ธุรกิจ การค้า-อุตสาหกรรม-คมนาคม อุตสาหกรรม-พลังงาน
     - https://mgronline.com/business/4450/4402/ #เศรษฐกิจ-ธุรกิจ การค้า-อุตสาหกรรม-คมนาคม คมนาคม-ขนส่ง
     - https://mgronline.com/business/4451/4409/ #new
     - https://mgronline.com/business/4511/ #new
     - https://mgronline.com/business/4512/ #new
     - https://mgronline.com/motoring/3201/ #Motoring ข่าวรถ
     - https://mgronline.com/motoring/3199/
     - https://mgronline.com/motoring/3215/
     - https://mgronline.com/motoring/3210/
     - https://mgronline.com/motoring/3204/
     - https://mgronline.com/cyberbiz/3501/3502/ #Cyber BIZ ข่าวไอที อิเล็กทรอนิกส์
     - https://mgronline.com/uptodate/
     - https://mgronline.com/local/1217/ #สังคมทั่วไทย new
     - https://mgronline.com/columnist/1423/ #new
     - https://mgronline.com/greeninnovation/1169/ #new
     - https://mgronline.com/greeninnovation/1166/ #new
     - https://mgronline.com/greeninnovation/1182/ #new
     - https://mgronline.com/greeninnovation/1171/ #new
     - https://mgronline.com/greeninnovation/1172/ #new
     - https://mgronline.com/politics/6023/
     - https://mgronline.com/politics/6051/
     - https://mgronline.com/politics/6002/
     - https://mgronline.com/sport/1322/1317/
     - https://mgronline.com/sport/premierleague/
     - https://mgronline.com/sport/laliga/
     - https://mgronline.com/sport/golf/1334/
     - https://mgronline.com/sport/golf/1335/
     - https://mgronline.com/around/9031/
     - https://mgronline.com/around/9040/9100/
     - https://mgronline.com/around/9040/9103/
     - https://mgronline.com/around/9040/9107/
     - https://mgronline.com/around/9040/9104/
     - https://mgronline.com/around/9040/9101/
     - https://mgronline.com/around/9040/9106/
     - https://mgronline.com/around/9040/9102/
     - https://mgronline.com/crime/4012/
     - https://mgronline.com/qol/8524/
     - https://mgronline.com/qol/8502/
     - https://mgronline.com/qol/8503/
     - https://mgronline.com/qol/8504/
     - https://mgronline.com/qol/8506/
  matichon:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 10
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_matichon:
     - https://www.matichon.co.th/lifestyle/tech/
     - https://www.matichon.co.th/stock-finance/stock-markets/ #หมวดใหม่
     - https://www.matichon.co.th/stock-finance/daily-stock-markets/
     - https://www.matichon.co.th/economy/auto/
     - https://www.matichon.co.th/local/ #หมวดใหม่
     - https://www.matichon.co.th/local/crime/ #หมวดใหม่
     - https://www.matichon.co.th/foreign/ #หมวดใหม่
     - https://www.matichon.co.th/lifestyle/health-beauty/ #หมวดใหม่
     - https://www.matichon.co.th/social/ #หมวดใหม่
     - https://www.matichon.co.th/article/ #หมวดใหม่
     - https://www.matichon.co.th/lifestyle/ #หมวดใหม่
     - https://www.matichon.co.th/region/ #หมวดใหม่
     - https://www.matichon.co.th/entertainment/ #หมวดใหม่
     - https://www.matichon.co.th/columnists/ #หมวดใหม่
     - https://www.matichon.co.th/covid19/
     - https://www.matichon.co.th/sport/
     - https://www.matichon.co.th/education/
     - https://www.matichon.co.th/politics/
  bkkbiznews:
    scheduler:
      - hour: 0
        minute: 0
      - hour: 2
        minute: 0
      - hour: 4
        minute: 0
      - hour: 6
        minute: 0
      - hour: 8
        minute: 0
      - hour: 10
        minute: 0
      - hour: 12
        minute: 0
      - hour: 14
        minute: 0
      - hour: 16
        minute: 0
      - hour: 18
        minute: 0
      - hour: 20
        minute: 0
      - hour: 22
        minute: 0
    since_datedelta: 0
    max_news_per_batch: 1000
    indexes_bkkbiznews:
     - https://www.bangkokbiznews.com/business/list/
     - https://www.bangkokbiznews.com/eec/list/
     - https://www.bangkokbiznews.com/auto/list/
     - https://www.bangkokbiznews.com/innovation/list/
     - https://www.bangkokbiznews.com/it/list/
     - https://www.bangkokbiznews.com/politics/list/
     - https://www.bangkokbiznews.com/bangkok/list/
     - https://www.bangkokbiznews.com/local/list/
     - https://www.bangkokbiznews.com/property/list/
     - https://www.bangkokbiznews.com/foreign/list/
     - https://www.bangkokbiznews.com/sport/list/
     - https://www.bangkokbiznews.com/travel/list/
     - https://www.bangkokbiznews.com/social/list/
     - https://www.bangkokbiznews.com/environment/list/
     - https://www.bangkokbiznews.com/education/list/
     - https://www.bangkokbiznews.com/life-style/list/
     - https://www.bangkokbiznews.com/judprakai-feature/list/
     - https://www.bangkokbiznews.com/judprakai-health-green/list/
  the_standard:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 10
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_the_standard:
     - https://thestandard.co/category/news/tech/
     - https://thestandard.co/category/news/business/
     - https://thestandard.co/category/news/world/
     - https://thestandard.co/category/news/politics/
     - https://thestandard.co/category/news/thailand/
     - https://thestandard.co/category/news/sport/
     - https://thestandard.co/category/news/environment/
     - https://thestandard.co/category/news/science/
outbound:
  post_news: http://news-classification:80/api/news
  drop_news: http://news-classification:80/api/news