db:
  username: postgres
  password: 1234
  host: localhost
  port: 5432
  database: postgres
  echo: False
logger:
  level: INFO
agency:
  dailynews:
    scheduler:
      - hour: 0
        minute: 0
      - hour: 12
        minute: 0
    since_datedelta: 14
    max_news_per_batch: 1000
    indexes:
      - https://www.dailynews.co.th/economic
  manageronline:
    scheduler:
      - hour: 0
        minute: 0
      - hour: 12
        minute: 0
      - hour: 15
        minute: 41
    since_datedelta: 14
    max_news_per_batch: 1000
    indexes:
      - https://mgronline.com/sport
outbound:
  post_news: http://localhost:8080/api/news
  drop_news: http://localhost:8080/api/news
