db:
  username: postgres
  password: "esl2"
  host: "localhost"
  port: 5432
  database: postgres
  echo: False
logger:
  level: INFO
agency:
  dailynews:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 55
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_dailynews:
    - https://www.dailynews.co.th/news/news_group/เศรษฐกิจ-ยานยนต์/
    - https://www.dailynews.co.th/news/news_group/ต่างประเทศ/
    - https://www.dailynews.co.th/news/news_group/การศึกษา-ไอที/
    - https://www.dailynews.co.th/news/news_group/อื่นๆ/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/บันเทิง/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/sport/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/politics-news/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/อาชญากรรม/ #หมวดใหม่
    - https://www.dailynews.co.th/news/news_group/ทั่วไทย-กทม/ #หมวดใหม่
  mgronline:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 55
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_mgronline:
     - https://mgronline.com/stockmarket/4920/ #หุ้น-Cryptocurrency
     - https://mgronline.com/stockmarket/4462/4458/
     - https://mgronline.com/stockmarket/4918/
     - https://mgronline.com/stockmarket/4461/4454/
     - https://mgronline.com/stockmarket/4904/
     - https://mgronline.com/stockmarket/4914/
     - https://mgronline.com/science/5516/5528/ #นวตกรรม
     - https://mgronline.com/science/5504/5530/ #อวกาศ
     - https://mgronline.com/science/5504/5519/
     - https://mgronline.com/science/5504/5531/ #ปรากฏการณ์
     - https://mgronline.com/science/5514/5532/ #เทคโนโลยีชีวภาพ
     - https://mgronline.com/science/5514/5526/
     - https://mgronline.com/science/5500/5501/ #news
     - https://mgronline.com/science/5500/5536/
     - https://mgronline.com/science/5500/5500/
     - https://mgronline.com/science/5517/5535/ #column
     - https://mgronline.com/science/5503/5509/ #nature
     - https://mgronline.com/science/5503/5510/
     - https://mgronline.com/science/5503/5511/
     - https://mgronline.com/science/5506/5512/ #research
     - https://mgronline.com/science/5506/5513/
     - https://mgronline.com/science/5506/5514/
     - https://mgronline.com/science/5506/5538/
     - https://mgronline.com/business/4450/4401/ #เศรษฐกิจ-ธุรกิจ การค้า-อุตสาหกรรม-คมนาคม อุตสาหกรรม-พลังงาน
     - https://mgronline.com/business/4450/4402/ #เศรษฐกิจ-ธุรกิจ การค้า-อุตสาหกรรม-คมนาคม คมนาคม-ขนส่ง
     - https://mgronline.com/business/4451/4409/ #new
     - https://mgronline.com/business/4511/ #new
     - https://mgronline.com/business/4512/ #new
     - https://mgronline.com/motoring/3201/ #Motoring ข่าวรถ
     - https://mgronline.com/motoring/3199/
     - https://mgronline.com/motoring/3215/
     - https://mgronline.com/motoring/3210/
     - https://mgronline.com/motoring/3204/
     - https://mgronline.com/cyberbiz/3501/3502/ #Cyber BIZ ข่าวไอที อิเล็กทรอนิกส์
     - https://mgronline.com/cyberbiz/3528/
     - https://mgronline.com/cyberbiz/3527/
     - https://mgronline.com/cyberbiz/3500/
     - https://mgronline.com/uptodate/
     - https://mgronline.com/local/1217/ #สังคมทั่วไทย new
     - https://mgronline.com/local/1204/
     - https://mgronline.com/local/1202/
     - https://mgronline.com/local/1203/
     - https://mgronline.com/local/1221/
     - https://mgronline.com/columnist/1423/ #new
     - https://mgronline.com/greeninnovation/1169/ #new
     - https://mgronline.com/greeninnovation/1166/ #new
     - https://mgronline.com/greeninnovation/1182/ #new
     - https://mgronline.com/greeninnovation/1171/ #new
     - https://mgronline.com/greeninnovation/1172/ #new
     - https://mgronline.com/politics/6023/
     - https://mgronline.com/politics/6051/
     - https://mgronline.com/politics/6002/
     - https://mgronline.com/sport/1322/1317/
     - https://mgronline.com/sport/premierleague/
     - https://mgronline.com/sport/laliga/
     - https://mgronline.com/sport/golf/1334/
     - https://mgronline.com/sport/golf/1335/
     - https://mgronline.com/sport/sports-news/
     - https://mgronline.com/sport/1324/
     - https://mgronline.com/sport/thaileague/
     - https://mgronline.com/sport/tennis/
     - https://mgronline.com/sport/1318/
     - https://mgronline.com/sport/1319/
     - https://mgronline.com/sport/1311/
     - https://mgronline.com/around/9031/
     - https://mgronline.com/around/9040/9100/
     - https://mgronline.com/around/9040/9103/
     - https://mgronline.com/around/9040/9107/
     - https://mgronline.com/around/9040/9104/
     - https://mgronline.com/around/9040/9101/
     - https://mgronline.com/around/9040/9106/
     - https://mgronline.com/around/9040/9102/
     - https://mgronline.com/crime/4012/
     - https://mgronline.com/qol/8524/
     - https://mgronline.com/qol/8502/
     - https://mgronline.com/qol/8503/
     - https://mgronline.com/qol/8504/
     - https://mgronline.com/qol/8506/
     - https://mgronline.com/smes/4524/
     - https://mgronline.com/travel/7501/
     - https://mgronline.com/travel/7522/
     - https://mgronline.com/travel/7509/
     - https://mgronline.com/travel/7549/
     - https://mgronline.com/travel/7531/
     - https://mgronline.com/travel/7573/
     - https://mgronline.com/travel/7537/
     - https://mgronline.com/travel/7538/
     - https://mgronline.com/entertainment/2903/
     - https://mgronline.com/entertainment/2200/
     - https://mgronline.com/entertainment/2926/
     - https://mgronline.com/entertainment/2100/
     - https://mgronline.com/entertainment/2608/
     - https://mgronline.com/game/9417/
     - https://mgronline.com/game/9404/
     - https://mgronline.com/game/9409/
     - https://mgronline.com/game/9405/
     - https://mgronline.com/game/9411/
     - https://mgronline.com/game/9401/
     - https://mgronline.com/game/9400/
     - https://mgronline.com/drama/2947/2801/
     - https://mgronline.com/drama/2947/2810/
     - https://mgronline.com/china/6531/7056/
     - https://mgronline.com/china/6531/7055/
     - https://mgronline.com/china/6531/7057/
     - https://mgronline.com/china/6531/7054/
     - https://mgronline.com/south/1223/
     - https://mgronline.com/south/1225/
     - https://mgronline.com/south/1234/
  matichon:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 55
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_matichon:
     - https://www.matichon.co.th/lifestyle/tech/
     - https://www.matichon.co.th/stock-finance/stock-markets/ #หมวดใหม่
     - https://www.matichon.co.th/stock-finance/daily-stock-markets/
     - https://www.matichon.co.th/economy/eco-report
     - https://www.matichon.co.th/economy/auto/
     - https://www.matichon.co.th/economy/
     - https://www.matichon.co.th/local/ #หมวดใหม่
     - https://www.matichon.co.th/local/quality-life/
     - https://www.matichon.co.th/local/crime/ #หมวดใหม่
     - https://www.matichon.co.th/foreign/ #หมวดใหม่
     - https://www.matichon.co.th/lifestyle/health-beauty/ #หมวดใหม่
     - https://www.matichon.co.th/social/ #หมวดใหม่
     - https://www.matichon.co.th/article/ #หมวดใหม่
     - https://www.matichon.co.th/lifestyle/ #หมวดใหม่
     - https://www.matichon.co.th/region/ #หมวดใหม่
     - https://www.matichon.co.th/entertainment/ #หมวดใหม่
     - https://www.matichon.co.th/columnists/ #หมวดใหม่
     - https://www.matichon.co.th/covid19/
     - https://www.matichon.co.th/sport/
     - https://www.matichon.co.th/education/
     - https://www.matichon.co.th/politics/
  bkkbiznews:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 55
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_bkkbiznews:
     - https://www.bangkokbiznews.com/business/list/
     - https://www.bangkokbiznews.com/eec/list/
     - https://www.bangkokbiznews.com/auto/list/
     - https://www.bangkokbiznews.com/innovation/list/
     - https://www.bangkokbiznews.com/it/list/
     - https://www.bangkokbiznews.com/politics/list/
     - https://www.bangkokbiznews.com/bangkok/list/
     - https://www.bangkokbiznews.com/local/list/
     - https://www.bangkokbiznews.com/property/list/
     - https://www.bangkokbiznews.com/foreign/list/
     - https://www.bangkokbiznews.com/sport/list/
     - https://www.bangkokbiznews.com/travel/list/
     - https://www.bangkokbiznews.com/social/list/
     - https://www.bangkokbiznews.com/environment/list/
     - https://www.bangkokbiznews.com/education/list/
     - https://www.bangkokbiznews.com/life-style/list/
     - https://www.bangkokbiznews.com/judprakai-feature/list/
     - https://www.bangkokbiznews.com/judprakai-health-green/list/
  the_standard:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 55
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_the_standard:
     - https://thestandard.co/category/news/tech/
     - https://thestandard.co/category/news/business/
     - https://thestandard.co/category/news/world/
     - https://thestandard.co/category/news/politics/
     - https://thestandard.co/category/news/thailand/
     - https://thestandard.co/category/news/sport/
     - https://thestandard.co/category/news/environment/
     - https://thestandard.co/category/news/science/
     - https://thestandard.co/category/culture/music/
     - https://thestandard.co/category/lifestyle/wellness/
     - https://thestandard.co/category/lifestyle/travel/
     - https://thestandard.co/category/lifestyle/living/
     - https://thestandard.co/category/lifestyle/eat-drink/
     - https://thestandard.co/category/news/china/
     - https://thestandard.co/category/wealth/wealth-cryptocurrency/
     - https://thestandard.co/category/culture/art-design/
     - https://thestandard.co/category/culture/film/
  prachachat:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 6
        minute: 15
      - hour: 15
        minute: 55
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_prachachat:
     - https://www.prachachat.net/finance/
     - https://www.prachachat.net/property/
     - https://www.prachachat.net/economy/
     - https://www.prachachat.net/local-economy/
     - https://www.prachachat.net/marketing/
     - https://www.prachachat.net/politics/
     - https://www.prachachat.net/world-news/
     - https://www.prachachat.net/general/
     - https://prachachat.net/motoring/
     - https://www.prachachat.net/ict/
     - https://www.prachachat.net/tourism/
     - https://www.prachachat.net/csr-hr/
     - https://www.prachachat.net/education/
  posttoday:
    scheduler:
      - hour: 0
        minute: 0
      - hour: 2
        minute: 0
      - hour: 4
        minute: 0
      - hour: 6
        minute: 0
      - hour: 8
        minute: 0
      - hour: 10
        minute: 0
      - hour: 12
        minute: 0
      - hour: 14
        minute: 0
      - hour: 16
        minute: 0
      - hour: 18
        minute: 0
      - hour: 20
        minute: 0
      - hour: 22
        minute: 0
    since_datedelta: 2
    max_news_per_batch: 1000
    indexes_posttoday:
     - https://www.posttoday.com/rss/src/politics.xml
     - https://www.posttoday.com/rss/src/entertainment.xml
     - https://www.posttoday.com/rss/src/world.xml
     - https://www.posttoday.com/rss/src/lifestyle.xml
     - https://www.posttoday.com/rss/src/economy.xml
     - https://www.posttoday.com/rss/src/money.xml
     - https://www.posttoday.com/rss/src/property.xml
     - https://www.posttoday.com/rss/src/sport.xml
     - https://www.posttoday.com/rss/src/social.xml
     - https://www.posttoday.com/rss/src/pr.xml

outbound:
  post_news: http://localhost:8080/api/news
  drop_news: http://localhost:8080/api/news
