db:
  username: postgres
  password: "esl2"
  host: "localhost"
  port: 5432
  database: postgres
  echo: False
logger:
  level: INFO
agency:
  dailynews:
    scheduler:
      - hour: 0
        minute: 0
      - hour: 12
        minute: 0
  mgronline:
    scheduler:
      - hour: 1
        minute: 0
      - hour: 13
        minute: 0
    since_datedelta: 1
    max_news_per_batch: 1000
    indexes_dailynews:
      - https://www.dailynews.co.th/economic
    indexes_mgronline:
      - https://mgronline.com/uptodate
outbound:
  post_news: http://localhost:8080/api/news
  drop_news: http://localhost:8080/api/news
