db:
  username: postgres
  password: esl2
  host: localhost
  port: 5432
  database: postgres
  echo: False
logger:
  level: INFO
agency:
  dailynews:
    since_datedelta: 1
    max_news_per_batch: 1000
    indexes:
      - https://www.dailynews.co.th/economic