TH_FULL_MONTHS_MAPPER = {
    "มกราคม": 'January',
    "กุมภาพันธ์": 'February',
    "มีนาคม": 'March',
    "เมษายน": 'April',
    "พฤษภาคม": 'May',
    "มิถุนายน": 'June',
    "กรกฎาคม": 'July',
    "สิงหาคม": 'August',
    "กันยายน": 'September',
    "ตุลาคม": 'October',
    "พฤศจิกายน": 'November',
    "ธันวาคม": 'December',
}

TH_FULL_MONTHS_MAPPER_MGR = {
    "ม.ค.": 'January',
    "ก.พ.": 'February',
    "มี.ค.": 'March',
    "เม.ย.": 'April',
    "พ.ค.": 'May',
    "มิ.ย.": 'June',
    "ก.ค.": 'July',
    "ส.ค.": 'August',
    "ก.ย.": 'September',
    "ต.ค.": 'October',
    "พ.ย.": 'November',
    "ธ.ค.": 'December',
}

TH_DAILYNEWS_CATEGORY_MAPPER = {
    "เศรษฐกิจ-ยานยนต์" : "economic","เศรษฐกิจจานร้อน" : "economic","มุมคนเมือง" : "economic","ป้ายแดงชวนขับ" : "economic",
    "รวมข่าวโควิด-19" : "economic", "ธุรกิจ" : "economic",
    "พาหนะคู่ใจ" : "economic","รู้ก่อนเหยียบ" : "economic",
    "การเมือง" : "politics","ที่เห็นที่เป็นอยู่" : "politics","คอลัมนิสต์" : "politics","เลียบค่ายกองทัพ" : "politics",
    "ตรวจการบ้าน" : "politics","ว่ายทวนน้ำ" : "politics",
    "เกษตร" : "agriculture",
    "ทั่วไทย-กทม." : "thailand","คนดีของสังคม" : "thailand","นิยายชีวิต" : "thailand","Special Report" : "thailand",
    "สังคมภูมิภาค" : "thailand","ส่องพระยอดนิยม" : "thailand",
    "การศึกษา-ไอที" : "education-it","การศึกษา" : "education-it","ไอที" : "education-it",
    "ท้องถิ่น" : "local", "ช่องทางทำกิน" : "local", "รายงานพิเศษ" : "local",
    "กีฬา" : "sports","Crazy Football" : "sports","สังคมกอล์ฟ" : "sports",
    "สุขภาพ-ความงาม" : "health-beauty",
    "อาชญากรรม" : "crime","หนอนโรงพัก" : "crime","สน.รอตรวจ" : "crime","เกาะประเด็นดัง" : "crime",
    "บันเทิง" : "entertainment","ดูหนังกับหมี" : "entertainment","1 Day with ซุปตาร์" : "entertainment","มายาลั้ลลา" : "entertainment",
    "บันเทิงต่างประเทศ" : "entertainment",
    "ต่างประเทศ" : "foreign","ผ่าโลกวันอาทิตย์" : "foreign","สารพันต่างแดน" : "foreign",
    "ที่นี่จากยูเอสเอ" : "foreign","คนไทยในออสเตรเลีย" : "foreign"
}

TH_BANGKOKBIZNEWS_CATEGORY_MAPPER = {
    "เศรษฐกิจ" : "economic",
    "การเมือง" : "politics",
    "การเงิน-การลงทุน" : "finance",
    "ธุรกิจ" : "business",
    "ต่างประเทศ" : "foreign",
    "bizweek" : "bizweek",
    "คุณภาพชีวิต-สังคม" : "life",
    "จุดประกาย" : "judprakai",
    "ไลฟ์สไตล์" : "lifestyle",
    "ข่าวประชาสัมพันธ์" : "pr",
    "ข่าวพระราชสำนัก" : "royal",
    "อาชญากรรม" : "crime",
    "ทั่วไทย" : "local",
    "บทวิเคราะห์" : "analysis",
    "EEC Focus" : "eec",
    "Big Data Analysis" : "bigdataanalysis",
    "ข้อมูลเศรษฐกิจ" : "data",
    "ยานยนต์" : "auto",
    "นวัตกรรม" : "innovation",
    "ไอที-ไอเดีย" : "it",
    "อสังหาริมทรัพย์" : "property",
}

TH_MATICHON_CATEGORY_MAPPER = {
    "เศรษฐกิจ" : "economy",
    "การเมือง" : "politics",
    "หุ้น-การเงิน" : "stock-finance",
    "ธุรกิจ" : "business",
    "ต่างประเทศ" : "foreign",
    "ไลฟ์สไตล์" : "lifestyle","สุขภาพ-ความงาม" : "lifestyle",
    "สังคม-สตรี" : "lifestyle","ดวง-โหราศาสตร์" : "lifestyle","อาหาร-ท่องเที่ยว" : "lifestyle","เด็ก-เยาวชน" : "lifestyle",
    "ข่าวพระราชสำนัก" : "royal",
    "อาชญากรรรม-กระบวนการยุติธรรม" : "crime", "อาชญากรรรม" : "crime",
    "ในประเทศ" : "local",
    "บทวิเคราะห์" : "analysis",
    "คอลัมนิสต์" : "columnists",
    "วิทยาการ-ไอที" : "tech",
    "นิวส์มอนิเตอร์" : "news-monitor",
    "รถยนต์" : "auto",
    "ภาวะหุ้นรายวัน" : "daily-stock-markets",
    "ตลาดหุ้น" : "stock-markets",
    "ภูมิภาค" : "region",
    "เกาะกระแสโซเชียล" : "social",
    "บันเทิง" : "entertainment",
    "ชีวิตคุณภาพ" : "quality-life",
    "บทความ" : "article", "สถานีคิดเลขที่ 12" : "article", "เดินหน้าชน" : "article", "คุณภาพคือความอยู่รอด" : "article",
    "เกาะติด Covid-19" : "covid19", "โควิด-ไทย" : "covid19",
    "กีฬา" : "sports", "เจาะลึกแดนอาทิตย์อุทัย" : "sports", "เกาะติดโตเกียวเกมส์" : "sports", "Sport Scoops" : "sports",
    "กีฬาต่างประเทศ" : "sports", "กีฬาในประเทศ" : "sports", "ฟุตบอลต่างประเทศ" : "sports", "ฟุตบอลในประเทศ" : "sports",
    "Sport Slide" : "sports", "โตเกียวเกมส์" : "sports", "มวย" : "sports"
}

TH_MANGERONLINE_CATEGORY_MAPPER = {
    "qol" : "quality-life",
    "around" : "foreign",
    "crime" : "crime",
    "sport" : "sports",
    "science" : "science",
    "uptodate" : "uptodate",
    "cyberbiz" : "cyberbiz",
    "motoring" : "motoring",
    "stockmarket" : "stockmarket",
    "business" : "business",
    "greeninnovation" : "greeninnovation",
    "columnist" : "columnist",
    "local" : "local",
    "politics" : "politics",
}

TAG_DELETE = ['Hot Shot! อินแจแปน','คลิปลุยโตเกียว 2020','แฟชั่น']

NEWS_MAX_NUM_PER_PAGE = 10